sharpsource/sharpsource.Test/SwitchIsMissingDefaultLabelTests.cs, sharpsource/sharpsource/Diagnostics/SwitchIsMissingDefaultLabel/SwitchIsMissingDefaultLabelAnalyzer.cs, sharpsource/sharpsource/Diagnostics/SwitchIsMissingDefaultLabel/SwitchIsMissingDefaultLabelCodeFix.cs, sharpsource/sharpsource/Utilities/Extensions.cs
=> Add System using directive when adding the default switch label

CHANGELOG.md, SharpSource/SharpSource.Test/Helpers/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/HttpContextStoredInFieldAnalyzerTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource/Diagnostics/HttpContextStoredInFieldAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs
=> HttpContextStoredInField

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/EnumWithoutDefaultValueTests.cs, SharpSource/SharpSource.Test/UnusedResultOnImmutableObjectTests.cs, SharpSource/SharpSource/Diagnostics/UnusedResultOnImmutableObjectAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> UnusedResultOnImmutableObject

CHANGELOG.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/UnusedResultOnImmutableObjectTests.cs, SharpSource/SharpSource/Diagnostics/UnusedResultOnImmutableObjectAnalyzer.cs
Closes #81 
Closes #82 
Closes #83 
Closes #85
=> Fixes multiple issues with `UnusedResultOnImmutableObject`

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/SharpSource.CodeFixes.csproj, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs, SharpSource/SharpSource.Test/ExceptionThrownFromProhibitedContextTests.cs, SharpSource/SharpSource.Test/TestMethodWithoutTestAttributeTests.cs, SharpSource/SharpSource/Diagnostics/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ExceptionThrownFromProhibitedContextAnalyzer.cs, SharpSource/SharpSource/Diagnostics/TestMethodWithoutTestAttributeAnalyzer.cs, SharpSource/SharpSource/SharpSource.csproj, SharpSource/SharpSource/Utilities/Extensions.cs
Closes #96 
Closes #91 
Closes #99 
Closes #98
=> Fix a bunch of bugs

CHANGELOG.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncOverloadsAvailableCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource.Test/EqualsAndGetHashcodeNotImplementedTogetherTests.cs, SharpSource/SharpSource/Diagnostics/AsyncOverloadsAvailableAnalyzer.cs, SharpSource/SharpSource/Diagnostics/EqualsAndGetHashcodeNotImplementedTogetherAnalyzer.cs
Closes #104 
Closes #103 
Closes #97 
Closes #94 
Closes #88
=> AsyncOverloadsAvailable bugs

CHANGELOG.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/EqualsAndGetHashcodeNotImplementedTogetherTests.cs, SharpSource/SharpSource.Test/GetHashCodeRefersToMutableMemberTests.cs, SharpSource/SharpSource/Diagnostics/EqualsAndGetHashcodeNotImplementedTogetherAnalyzer.cs, SharpSource/SharpSource/Diagnostics/GetHashCodeRefersToMutableMemberAnalyzer.cs
=> Fixes a few bugs related to partials

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncMethodWithVoidReturnTypeCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AccessingTaskResultWithoutAwaitTests.cs, SharpSource/SharpSource.Test/AsyncMethodWithVoidReturnTypeTests.cs, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource.Test/ThreadSleepInAsyncMethodTests.cs, SharpSource/SharpSource.Test/UnusedResultOnImmutableObjectTests.cs, SharpSource/SharpSource/Diagnostics/AccessingTaskResultWithoutAwaitAnalyzer.cs, SharpSource/SharpSource/Diagnostics/AsyncMethodWithVoidReturnTypeAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadSleepInAsyncMethodAnalyzer.cs, SharpSource/SharpSource/Utilities/Extensions.cs
closes #112 
closes #111 
closes #110 
closes #108
=> Support ValueTask

CHANGELOG.md, README.md, SharpSource/SharpSource.Test/ExceptionThrownFromProhibitedContextTests.cs, SharpSource/SharpSource.Test/Helpers/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/OnPropertyChangedWithoutNameOfOperatorTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource.Test/TestMethodWithoutPublicModifierTests.cs, SharpSource/SharpSource.Test/TestMethodWithoutTestAttributeTests.cs, SharpSource/SharpSource.Test/UnusedResultOnImmutableObjectTests.cs, SharpSource/SharpSource/Diagnostics/TestMethodWithoutTestAttributeAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs
closes #130 
closes #125 
closes #122
=> Improved documentation

.github/workflows/build.yml, .github/workflows/format.yml, .github/workflows/release.yml, .github/workflows/version-bump-check.yml, CHANGELOG.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource/Diagnostics/FlagsEnumValuesAreNotPowersOfTwoAnalyzer.cs, nuget.config
=> Version Bump Check CI

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/NewGuidCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/UnboundedStackallocCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource.Test/UnboundedStackallocTests.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnboundedStackallocAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> StaticInitializerAccessedBeforeInitialization & UnboundedStackalloc

CHANGELOG.md, CONTRIBUTING.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AttributeMustSpecifyAttributeUsageCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ExplicitEnumValuesTests.cs, SharpSource/SharpSource.Test/LinqTraversalBeforeFilterTests.cs, SharpSource/SharpSource.Test/LockingOnDiscouragedObjectTests.cs, SharpSource/SharpSource/Diagnostics/GetHashCodeRefersToMutableMemberAnalyzer.cs, SharpSource/SharpSource/Diagnostics/LinqTraversalBeforeFilterAnalyzer.cs, SharpSource/SharpSource/Diagnostics/LockingOnDiscouragedObjectAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnnecessaryEnumerableMaterializationAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs
=> LinqTraversalBeforeFilter

.github/workflows/build.yml, .github/workflows/changelog-check.yml, .github/workflows/format.yml, .github/workflows/version-bump-check.yml, CHANGELOG.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs
closes #171 
closes #172 
closes #173
=> StaticInitializerAccessedBeforeInitialization defects

CHANGELOG.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/DivideIntegerByIntegerTests.cs, SharpSource/SharpSource.Test/LoopedRandomInstantiationTests.cs, SharpSource/SharpSource.Test/OnPropertyChangedWithoutNameOfOperatorTests.cs, SharpSource/SharpSource.Test/RethrowExceptionWithoutLosingStracktraceTests.cs, SharpSource/SharpSource.Test/StringDotFormatWithDifferentAmountOfArgumentsTests.cs, SharpSource/SharpSource.Test/StringPlaceholdersInWrongOrderTests.cs, SharpSource/SharpSource.Test/SwitchDoesNotHandleAllEnumOptionsTests.cs, SharpSource/SharpSource.Test/TestMethodWithoutPublicModifierTests.cs
=> Warning messages in tests are hardcoded

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/NewGuidCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/HttpClientInstantiatedDirectlyTests.cs, SharpSource/SharpSource.Test/NewGuidTests.cs, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource/Diagnostics/HttpClientInstantiatedDirectlyAnalyzer.cs, SharpSource/SharpSource/Diagnostics/NewGuidAnalyzer.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> supports implicit object creation expressions

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncMethodWithVoidReturnTypeCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/ComparingStringsWithoutStringComparisonCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/FlagsEnumValuesAreNotPowersOfTwoCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/SwitchDoesNotHandleAllEnumOptionsCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/UnnecessaryEnumerableMaterializationCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource.Test/UnnecessaryEnumerableMaterializationTests.cs, SharpSource/SharpSource/Diagnostics/AsyncOverloadsAvailableAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ComparingStringsWithoutStringComparisonAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ExceptionThrownFromProhibitedContextAnalyzer.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs, SharpSource/SharpSource/Diagnostics/StructWithoutElementaryMethodsOverriddenAnalyzer.cs, SharpSource/SharpSource/Diagnostics/SwitchDoesNotHandleAllEnumOptionsAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadSleepInAsyncMethodAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnboundedStackallocAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnnecessaryEnumerableMaterializationAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, SharpSource/SharpSource/Utilities/Extensions.cs, docs/SS049-ComparingStringsWithoutStringComparison.md
=> Comparing strings without string comparison

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> AddUsingStatementIfMissing correctness

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/ParameterAssignedInConstructorCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/ParameterAssignedInConstructorTests.cs, SharpSource/SharpSource/Diagnostics/ParameterAssignedInConstructorAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, SharpSource/SharpSource/Utilities/Extensions.cs, docs/SS050-ParameterAssignedInConstructor.md
=> ParameterAssignedInConstructor

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/ComparingStringsWithoutStringComparisonCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/LockingOnMutableReferenceCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/LockingOnMutableReferenceTests.cs, SharpSource/SharpSource.Test/UnusedResultOnImmutableObjectTests.cs, SharpSource/SharpSource/Diagnostics/LockingOnMutableReferenceAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnusedResultOnImmutableObjectAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS051-LockingOnMutableReference.md
closes #201
closes #162
closes #86
=> LockingOnMutableReference

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AccessingTaskResultWithoutAwaitCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AccessingTaskResultWithoutAwaitTests.cs, SharpSource/SharpSource/Diagnostics/AccessingTaskResultWithoutAwaitAnalyzer.cs
=> AccessingTaskResultWithoutAwait improvements

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource.Test/ThreadStaticWithInitializerTests.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadStaticWithInitializerAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS052-ThreadStaticWithInitializer.md
=> ThreadStaticWithInitializer

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/PointlessCollectionToStringTests.cs, SharpSource/SharpSource.Test/UnnecessaryEnumerableMaterializationTests.cs, SharpSource/SharpSource/Diagnostics/PointlessCollectionToStringAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, SharpSource/SharpSource/Utilities/Extensions.cs, docs/SS052-ThreadStaticWithInitializer.md, docs/SS053-PointlessCollectionToString.md
=> PointlessCollectionToString

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/StaticInitializerAccessedBeforeInitializationTests.cs, SharpSource/SharpSource/Diagnostics/StaticInitializerAccessedBeforeInitializationAnalyzer.cs
Re-wrote the analyzer in a simplified way not relying on syntax.
=> Simplify SS045 (StaticInitializerAccessedBeforeInitializationAnalyzer)

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource/Diagnostics/SwitchDoesNotHandleAllEnumOptionsAnalyzer.cs
This might improve the performance (#148).
@Vannevelj Could you confirm if this fixes the performance problem?
Either way, using `IOperation` is simpler and better here.
=> Re-write SS018 using IOperation

.github/workflows/build.yml, .github/workflows/test.yml, CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/PointlessCollectionToStringTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource/Diagnostics/InstanceFieldWithThreadStaticAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadStaticWithInitializerAnalyzer.cs
=> More IOperation for ThreadStatic analyzers

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs, SharpSource/SharpSource.Test/LinqTraversalBeforeFilterTests.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> ElementaryMethodsOfTypeInCollectionNotOverridden: Fixed a `NullReferenceException` when analysing `extern` declarations

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/NewtonsoftMixedWithSystemTextJsonTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource/Diagnostics/NewtonsoftMixedWithSystemTextJsonAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS054-NewtonsoftMixedWithSystemTextJson.md.md
=> NewtonsoftMixedWithSystemTextJson

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/ComparingStringsWithoutStringComparisonCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/SynchronousTaskWaitCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource.Test/SynchronousTaskWaitTests.cs, SharpSource/SharpSource.Test/ThreadSleepInAsyncMethodTests.cs, SharpSource/SharpSource/Diagnostics/SynchronousTaskWaitAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadSleepInAsyncMethodAnalyzer.cs
closes #263 
closes #245 
closes #256
=> SynchronousTaskWait 

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncOverloadsAvailableCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/ComparingStringsWithoutStringComparisonCodeFix.cs, SharpSource/SharpSource.CodeFixes/Utilities/Extensions.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource/Diagnostics/ComparingStringsWithoutStringComparisonAnalyzer.cs, SharpSource/SharpSource/Utilities/IsExternalInit.cs
=> AsyncOverloadsAvailable_Chained

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncMethodWithVoidReturnTypeCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/AttributeMustSpecifyAttributeUsageCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/ComparingStringsWithoutStringComparisonCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/SwitchIsMissingDefaultLabelCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/ThreadSleepInAsyncMethodCodeFix.cs, SharpSource/SharpSource.CodeFixes/Utilities/Extensions.cs, SharpSource/SharpSource.CodeFixes/Utilities/SymbolAnnotation.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AsyncMethodWithVoidReturnTypeTests.cs, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/SwitchIsMissingDefaultLabelTests.cs, SharpSource/SharpSource/Diagnostics/AsyncMethodWithVoidReturnTypeAnalyzer.cs
=> Replace all AddUsingStatementIfMissing

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AccessingTaskResultWithoutAwaitTests.cs, SharpSource/SharpSource.Test/AsyncMethodWithVoidReturnTypeTests.cs, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource.Test/AttributeMustSpecifyAttributeUsageTests.cs, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/DateTimeNowTests.cs, SharpSource/SharpSource.Test/DivideIntegerByIntegerTests.cs, SharpSource/SharpSource.Test/Helpers/CSCodeFix+Test.cs, SharpSource/SharpSource.Test/Helpers/CSCodeFix.cs, SharpSource/SharpSource.Test/Helpers/CSHelper.cs, SharpSource/SharpSource.Test/Helpers/DiagnosticVerifier.cs, SharpSource/SharpSource.Test/HttpClientInstantiatedDirectlyTests.cs, SharpSource/SharpSource.Test/HttpContextStoredInFieldTests.cs, SharpSource/SharpSource.Test/InstanceFieldWithThreadStaticTests.cs, SharpSource/SharpSource.Test/MultipleFromBodyParametersTests.cs, SharpSource/SharpSource.Test/NewGuidTests.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource.Test/ThreadStaticWithInitializerTests.cs
WIP #274
Current issues:
* `MultipleFromBodyParametersTests` doesn't have a code fix but a second generic type parameter is required
* I want to accept both top-level statements and others without additional configuration but I can't seem to ignore `CS5001`
=> added a few VerifyCS

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/MultipleOrderByCallsCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/Helpers/CSCodeFix+Test.cs, SharpSource/SharpSource.Test/MultipleOrderByCallsTests.cs, SharpSource/SharpSource.Test/TestMethodWithoutTestAttributeTests.cs, SharpSource/SharpSource/Diagnostics/MultipleOrderByCallsAnalyzer.cs, SharpSource/SharpSource/Diagnostics/TestMethodWithoutTestAttributeAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS055-MultipleOrderByCalls.md
closes #279 
closes #278 
closes #155
=> TestMethodWithoutTestAttributeTests uses VerifyCS

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/FormReadSynchronouslyTests.cs, SharpSource/SharpSource.Test/Helpers/CSCodeFix+Test.cs, SharpSource/SharpSource.Test/NewtonsoftMixedWithSystemTextJsonTests.cs, SharpSource/SharpSource.Test/SwitchIsMissingDefaultLabelTests.cs, SharpSource/SharpSource/Diagnostics/FormReadSynchronouslyAnalyzer.cs, SharpSource/SharpSource/Diagnostics/SwitchIsMissingDefaultLabelAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS055-MultipleOrderByCalls.md, docs/SS056-FormReadSynchronously.md
=> FormReadSynchronously

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/LinqTraversalBeforeFilterTests.cs, SharpSource/SharpSource.Test/LockingOnDiscouragedObjectTests.cs, SharpSource/SharpSource.Test/LockingOnMutableReferenceTests.cs, SharpSource/SharpSource.Test/StringConcatenatedInLoopTests.cs, SharpSource/SharpSource/Diagnostics/StringConcatenatedInLoopAnalyzer.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS058-StringConcatenatedInLoop.md
=> StringConcatenatedInLoop

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/AsyncOverloadsAvailableCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/StringPlaceholdersInWrongOrderCodeFix.cs, SharpSource/SharpSource.CodeFixes/Diagnostics/ThreadSleepInAsyncMethodCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AsyncMethodWithVoidReturnTypeTests.cs, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource.Test/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs, SharpSource/SharpSource.Test/LoopedRandomInstantiationTests.cs, SharpSource/SharpSource.Test/ParameterAssignedInConstructorTests.cs, SharpSource/SharpSource.Test/StringConcatenatedInLoopTests.cs, SharpSource/SharpSource.Test/StringPlaceholdersInWrongOrderTests.cs, SharpSource/SharpSource.Test/UnboundedStackallocTests.cs, SharpSource/SharpSource/Diagnostics/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ParameterAssignedInConstructorAnalyzer.cs, SharpSource/SharpSource/Diagnostics/StringPlaceholdersInWrongOrderAnalyzer.cs, SharpSource/SharpSource/Diagnostics/UnboundedStackallocAnalyzer.cs, docs/SS004-ElementaryMethodsOfTypeInCollectionNotOverridden.md, docs/SS005-EqualsAndGetHashcodeNotImplementedTogether.md, docs/SS055-MultipleOrderByCalls.md
closes #302 
closes #289 
closes #299 
closes #297 
closes #306 
closes #300
=> `ParameterAssignedInConstructor` improvements

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ComparingStringsWithoutStringComparisonTests.cs, SharpSource/SharpSource.Test/SwitchDoesNotHandleAllEnumOptionsTests.cs, SharpSource/SharpSource/Diagnostics/ComparingStringsWithoutStringComparisonAnalyzer.cs, SharpSource/SharpSource/Diagnostics/SwitchDoesNotHandleAllEnumOptionsAnalyzer.cs, docs/SS018-SwitchDoesNotHandleAllEnumOptions.md
=> SwitchDoesNotHandleAllEnumOptions severity

CHANGELOG.md, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/DisposeAsyncDisposableCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/DisposeAsyncDisposableTests.cs, SharpSource/SharpSource.Test/StringConcatenatedInLoopTests.cs, SharpSource/SharpSource.Test/TestMethodWithoutTestAttributeTests.cs, SharpSource/SharpSource/Diagnostics/StringConcatenatedInLoopAnalyzer.cs, SharpSource/SharpSource/Diagnostics/TestMethodWithoutTestAttributeAnalyzer.cs
closes #330 
closes #331 
closes #329
=> StringConcatenatedInLoop: No longer triggers a warning if the string is retrieved through an indexer

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/AsyncOverloadsAvailableTests.cs, SharpSource/SharpSource/Diagnostics/AsyncOverloadsAvailableAnalyzer.cs, SharpSource/SharpSource/Diagnostics/DisposeAsyncDisposableAnalyzer.cs, SharpSource/SharpSource/Diagnostics/SynchronousTaskWaitAnalyzer.cs, SharpSource/SharpSource/Diagnostics/ThreadSleepInAsyncMethodAnalyzer.cs, SharpSource/SharpSource/Utilities/Extensions.cs
=> `AsyncOverloadsAvailable` housekeeping

CHANGELOG.md, Directory.Packages.props, README.md, SharpSource/SharpSource.CodeFixes/Diagnostics/ConcurrentDictionaryEmptyCheckCodeFix.cs, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ConcurrentDictionaryEmptyCheckTests.cs, SharpSource/SharpSource.Test/Helpers/CSCodeFix+Test.cs, SharpSource/SharpSource.Test/Helpers/CSCodeFix.cs, SharpSource/SharpSource.Test/SharpSource.Test.csproj, SharpSource/SharpSource/Diagnostics/ConcurrentDictionaryEmptyCheck.cs, SharpSource/SharpSource/Utilities/DiagnosticId.cs, docs/SS060-ConcurrentDictionaryEmptyCheck.md
=> Implements ConcurrentDictionaryEmptyCheck

CHANGELOG.md, README.md, SharpSource/SharpSource.Package/SharpSource.Package.csproj, SharpSource/SharpSource.Test/ElementaryMethodsOfTypeInCollectionNotOverriddenTests.cs, SharpSource/SharpSource/Diagnostics/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs
=> Add .Distinct() and .ToHashSet() diagnostics to ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer
